name: Backend CD
on: push:
branches: [ main ]
jobs:
deploy:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v4
- name: Trigger Render Deploy
run: |
curl -X POST -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
-H "Content-Type: application/json" \
-d '{}' \
"https://api.render.com/deploy/srv-xxxxxxxxxxxxxxxx"